global:
  scrape_interval: 5s
  evaluation_interval: 5s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cloudwatch_exporter'
    static_configs:
      - targets: ['cloudwatch_exporter:9106']
      
  # Add Pushgateway scraping for Lambda metrics
  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: 5s  # Keep labels set by the Pushgateway
    static_configs:
      - targets: ['pushgateway:9091']